name:                SuccinctDeBruijnGraph
version:             0.1.0.0
license:             BSD3
author:              "Andrey Chertkov"
maintainer:          "a.chertkov@innopolis.ru"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README

custom-setup:
  dependencies:
  - containers
  - vector
  - hashmap
  - base >= 4.7 && < 5
  - Cabal
  - cabal-doctest >=1.0.2 && <1.1

ghc-options:
- -Wall -fno-warn-type-defaults

dependencies:
- containers
- vector
- hashmap
- split
- base >= 4.7 && < 5
- doctest
- fasta
- text
- graphviz
- Unique
- hw-packed-vector
- hw-prim

library:
  source-dirs: 
  - src

executables:
  SuccinctDeBruijnGraph-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - SuccinctDeBruijnGraph

tests:
  spec:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - SuccinctDeBruijnGraph
    - hspec
    - hspec-core
    - HUnit
    - QuickCheck
    - doctest
    - containers
    - vector
    - hashmap
    - split
    - base >= 4.7 && < 5

  doctests:
    source-dirs: test
    main: doctests.hs
    other-modules: []
    dependencies:
    - base
    - doctest
    - Glob
    - QuickCheck
    - template-haskell

benchmarks:
  bench:
    main:                Main.hs
    source-dirs:         bench
    ghc-options:
    - -threaded
    - -O2
    - -rtsopts
    - -with-rtsopts=-N
    - -ddump-simpl
    dependencies:
    - criterion
    - SuccinctDeBruijnGraph